SELECT E.COMPANY, E.PAYGROUP, TO_CHAR(E.PAY_END_DT,'YYYY-MM-DD'), E.OFF_CYCLE, E.PAGE_NUM, E.LINE_NUM, E.EMPLID, e.OK_TO_PAY
  FROM PS_PAY_CALENDAR A, PS_PAY_EARNINGS E 
  WHERE A.RUN_ID = :1 
     AND A.COMPANY = E.COMPANY 
     AND A.PAYGROUP = E.PAYGROUP 
     AND A.PAY_END_DT = E.PAY_END_DT 
     and e.OK_TO_PAY = 'Y'
     AND EXISTS (SELECT 'X' 
  FROM PS_PAY_EARNINGS C, PS_PAY_CALENDAR D 
  WHERE D.RUN_ID = A.RUN_ID 
     AND C.COMPANY = D.COMPANY 
     AND C.PAYGROUP = D.PAYGROUP 
     AND C.PAY_END_DT = D.PAY_END_DT 
     AND C.EMPLID = E.EMPLID 
     AND C.PAYGROUP <> E.PAYGROUP 
     AND C.OK_TO_PAY = 'Y')